### ISSUE TITLE
Crash when running app with Jibber

### ISSUE THREAD

**Issue by schayes04** [rebeltools/Jibber-Framework#1]
I have a project that works fine normally but when I add the Jibber framework it crashes on startup. I am using RESTKit for networking which relies on NSUrlConnection. I have Jibber working successfully on another project with the same version of RESTKit.

The crash is as follows:

2015-04-08 14:40:30.220 App[5690:97012] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[NSProxy methodSignatureForSelector:] called!'

**\* First throw call stack:

(

0   CoreFoundation                      0x000000010b9efa75 __exceptionPreprocess + 165

1   libobjc.A.dylib                     0x000000010b688bb7 objc_exception_throw + 45

2   CoreFoundation                      0x000000010b9ef9ad +[NSException raise:format:] + 205

3   Foundation                          0x000000010b2cc7d2 -[NSProxy methodSignatureForSelector:] + 43

4   CoreFoundation                      0x000000010b94e720 **_forwarding**_ + 288

5   CoreFoundation                      0x000000010b94e578 _CF_forwarding_prep_0 + 120

6   CFNetwork                           0x0000000107e94935 ___ZL31_NSURLConnectionWillSendRequestP16_CFURLConnectionPK13_CFURLRequestP14_CFURLResponsePKv_block_invoke + 146

7   CFNetwork                           0x0000000107ea898c __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 69

8   Foundation                          0x000000010b2c55af **NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK** + 7

9   Foundation                          0x000000010b2053b2 -[NSBlockOperation main] + 98

10  Foundation                          0x000000010b1e7ac4 -[__NSOperationInternal _start:] + 645

11  Foundation                          0x000000010b1e76d3 __NSOQSchedule_f + 184

12  libdispatch.dylib                   0x000000010c7a4614 _dispatch_client_callout + 8

13  libdispatch.dylib                   0x000000010c78b6a7 _dispatch_queue_drain + 2176

14  libdispatch.dylib                   0x000000010c78acc0 _dispatch_queue_invoke + 235

15  libdispatch.dylib                   0x000000010c78e3b9 _dispatch_root_queue_drain + 1359

16  libdispatch.dylib                   0x000000010c78fb17 _dispatch_worker_thread3 + 111

17  libsystem_pthread.dylib             0x000000010cb29637 _pthread_wqthread + 729

18  libsystem_pthread.dylib             0x000000010cb2740d start_wqthread + 13

)

libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by matthewcheok** [comment]
Should be fixed in 1.3.5

**Comment by schayes04** [comment]
thanks!
